# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46582c317bca91f8af7316fe89bbd1edc53cbb6d480dd64e8b72dde571a52343f3076280aa08f603e2e9343d25b8907fda1a7a2c3040f758d2e198c91483ec6e

test:
  secret_key_base: 2cb1f698cefe3b24d993f783c49a8993b4e155ded2d9c3ca273a24073cae3339928657ee1fb407f4d2e4ec25692329d159a6f579983d775b244afaf97cae9a96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
